import pandas as pd
import numpy as np

class SimulatorEngine:
    """
    Engine to calculate and simulate backtest performance.
    """
    def __init__(self, data: pd.DataFrame, initial_capital: float = 10000.0):
        self.data = data.copy()
        self.initial_capital = initial_capital

    def run(self) -> pd.DataFrame:
        """
        Runs the simulation based on 'position' column in data.
        Returns the DataFrame with additional performance metrics.
        """
        if 'position' not in self.data.columns:
            raise ValueError("Data must compel a 'position' column generated by a strategy.")
            
        # Daily return of the asset itself
        self.data['market_return'] = self.data['close'].pct_change()
        
        # Strategy return: Asset return * Position
        # position=1 means we hold the asset, position=0 means we hold cash
        self.data['strategy_return'] = self.data['market_return'] * self.data['position']
        
        # Cumulative returns
        # Using cumulative product: Cum_Ret = (1 + r_t) * (1 + r_{t-1}) ...
        self.data['market_cum_return'] = (1 + self.data['market_return'].fillna(0)).cumprod()
        self.data['strategy_cum_return'] = (1 + self.data['strategy_return'].fillna(0)).cumprod()
        
        # Portfolio value over time
        self.data['portfolio_value'] = self.initial_capital * self.data['strategy_cum_return']
        
        return self.data

    def get_summary(self) -> dict:
        """
        Returns a summary of the backtest.
        """
        if 'strategy_cum_return' not in self.data.columns:
            return {}
            
        total_market_return = (self.data['market_cum_return'].iloc[-1] - 1) * 100
        total_strategy_return = (self.data['strategy_cum_return'].iloc[-1] - 1) * 100
        
        # Max Drawdown Calculation
        cum_max = self.data['strategy_cum_return'].cummax()
        drawdown = (self.data['strategy_cum_return'] - cum_max) / cum_max
        max_drawdown = drawdown.min() * 100
        
        return {
            "Total Market Return (%)": round(total_market_return, 2),
            "Total Strategy Return (%)": round(total_strategy_return, 2),
            "Max Drawdown (%)": round(max_drawdown, 2),
            "Final Portfolio Value": round(self.data['portfolio_value'].iloc[-1], 2)
        }
